### ISSUE TITLE
veri çekme

### ISSUE THREAD

**Issue by parzival-au20** [parzival-au20/sefa#44]
import pandas as pd
from src import PullNews
from src import SelenTaker
import ssl
import re
ctx = ssl.create_default_context()
ctx.check_hostname = False
ctx.verify_mode = ssl.CERT_NONE

class VerticalTaker(SelenTaker,PullNews):
    def __init__(self, web_site_name, category_name, js_file_name,news_link):
        super().__init__()
        self.web_site_name = web_site_name
        self.category_name = category_name
        self.news_bound=400
        self.news_number=10
        self.news_link=news_link
    def main(self,BeautyTaker):

            page_number = 1
            
            self.BeautyTaker = BeautyTaker
            while True:
                try:
                    if(self.news_bound>=page_number*self.news_number):
                        self.create_urllib_object(f"https://verticalmag.com/news/page/{page_number}/")
                    
                        bs4Obj=self.read_website_by_urllib()
                        if(bs4Obj==None):
                            self.convert_to_csv()
                            break
                        div_elements=bs4Obj.findAll("div",class_="col-12 col-md-4")
                        #convert links and image links
                        self.Links=""
                        self.Image_links=""
                        
                        for div in div_elements:
                            try:
                                #links
                                self.Links=self.Links+str(div.findAll("a",href=True)[0]["href"])+","
                                #-----------------
                                #image links

                                self.Image_links=self.Image_links+str(div.findAll("img")[0]["src"])+","
                                #---------------------
                            except Exception as e:
                                    print(e)
                        link_array = str(self.Links).strip(",").split(",")
                        image_link_array = str(self.Image_links).strip(",").split(",")
                        #------------------------
                        
                        #haber ekleme
                        self.add_content(link_array,image_link_array)    
                        
                        
                        if(self.is_stop==True):
                            self.convert_to_csv()
                            break
                        else:
                            page_number=page_number+1
                    else:
                        self.convert_to_csv()
                        break
                except Exception as e:
                    print(e)

    

class BeautyVertical(PullNews):
    def __init__(self):
        super().__init__()

    def get_text_by_element(self, news_link) -> dict:
        
            link=news_link
            self.create_urllib_object(link)
            
            bs4Obj=self.read_website_by_urllib()
         
            """pull title"""
            title=bs4Obj.find(
                "h1", {"class": "card-title"}).get_text()

            
            """pull text"""
            p_elements=bs4Obj.select("div.entry-content")
            text=""
            for p in p_elements:
                for _p in p.findAll("p"):
                    text=text+str(_p.get_text())
            
            """pull timestamp"""
            re_pattern=r"(\w* \d*, \d*)"
            time_stamp=bs4Obj.find("div",{"class": "author-title"}).get_text()
            matched_time_stamp=re.findall(re_pattern, time_stamp)[0]
            
            return self.outcome_control(title,text,matched_time_stamp)

**Comment by parzival-au20** [comment]
- Prod-To\MedyaTakip2\Form1.cs(1956,43,1956,53): error CS7036: There is no argument given that corresponds to the required formal parameter 'multipliedLeading' of 'Phrase.SetLeading(float, float)'

**Comment by parzival-au20** [comment]
def main(self,BeautyTaker):

            page_number = 1
            
            self.BeautyTaker = BeautyTaker
            while True:
                try:
                    if(self.news_bound>=page_number*self.news_number):
                        self.create_urllib_object(f"https://verticalmag.com/news/page/{page_number}/")
                    
                        bs4Obj=self.read_website_by_urllib()
                        if(bs4Obj==None):
                            self.convert_to_csv()
                            break
                        div_elements=bs4Obj.findAll("div",class_="col-12 col-md-4")
                        #convert links and image links
                        self.Links=""
                        self.Image_links=""
                        
                        for div in div_elements:
                            try:
                                #links
                                self.Links=self.Links+str(div.findAll("a",href=True)[0]["href"])+","
                                #-----------------
                                #image links

                                self.Image_links=self.Image_links+str(div.findAll("img")[0]["src"])+","
                                #---------------------
                            except Exception as e:
                                    print(e)
                        link_array = str(self.Links).strip(",").split(",")
                        image_link_array = str(self.Image_links).strip(",").split(",")
                        #------------------------
                        
                        #haber ekleme
                        self.add_content(link_array,image_link_array)    
                        
                        
                        if(self.is_stop==True):
                            self.convert_to_csv()
                            break
                        else:
                            page_number=page_number+1
                    else:
                        self.convert_to_csv()
                        break
                except Exception as e:
                    print(e)

**Comment by parzival-au20** [comment]
def add_content(self,link_array,image_link_array,lokheedmartin_flag=None):

            old_date=""
                                
            content = None
                        
            for i,image in zip(link_array,image_link_array):
                try:
                    if(self.is_stop==True):
                        break
                    
                    content = self.BeautyTaker.get_text_by_element(i)
                    old_date=content["timestamp"]
                    content["category"] = self.category_name
                    content["web_site_name"] = self.web_site_name
                    content["Url"]=i
                    content["image"]=image
                    content["title"] = content["title"].replace("½", "half")
                    content["text"] = content["text"].replace("½", "half")
                    content["timestamp"]=self.text_to_date(content["timestamp"])
                    
                    
                    if(self.control_text_by(old_date)==True or self.control_text_by(old_date)=="writing"):
                        if(content["text"].lower().find("helicopter")!=-1 or content["text"].lower().find("helikopter")!=-1):
                            df_content=pd.DataFrame(content,index=[0])
                            self.data_frame_news=self.data_frame_news.append(df_content,ignore_index=True)   
                            self.counter=self.counter+1
                            print(content)
                        else:
                            continue
                    else:
                        self.is_stop=True
                        

                except Exception as e:
                        if("HTTP Error" in str(e)):
                            self.is_stop=True
                        print(e)
            del link_array
            del content

**Comment by parzival-au20** [comment]
class SelenTaker:
    def __init__(self):
        """bu fonksiyon classın constructure dir """
        self.formatType={'VerticalMag':['%B %d, %Y',"english"],'SavunmaSanayist':['%d %B %Y',"turkish"],'RotorAndWing':['%B %d, %Y','english'],'Leonardo':['%d %B %Y','english'],
        'HeliHub':['%d-%b-%Y','english'],'helicoptersmagazine':['%B %d, %Y','english'],'DefenceTurkey':['%d %B, %Y','turkish'],'DefenceTurk':['%d %b %Y','turkish'],'lockheedmartin':['%b. %d, %Y','english']
        ,'JustHelicopters':['%d.%m.%Y',"english"]}
        self.data_frame_news=pd.DataFrame(columns=["Url","category","image","text","timestamp","title","web_site_name"])
        self.web_site_name=None
        self.BeautyTaker=None
        self.category_name=None
        self.save_date_file_loc=".\\WebSiteDates"
        self.counter=0
        self.default_format_type="%d.%m.%Y"
        self.is_stop=False
        self.counter_http_error=0

**Comment by parzival-au20** [comment]
def convert_to_csv(self):
       while True: 
            file_number=0
            if not os.path.exists(f"./{self.web_site_name}-{file_number}"):

                self.data_frame_news.to_csv(f"./{self.web_site_name}-{file_number}.csv",index=False,sep="½",encoding='utf-8-sig',)
                self.write_date(self.date_to_text(datetime.datetime.today()))
                break
            else:
                file_number=file_number+1

**Comment by parzival-au20** [comment]
"""pull text"""
            p_elements=bs4Obj.select("div.wrap.ComponentWrap_wrap__f7e25")
            text=""
            for p in p_elements:
                    text=text+str(p.get_text())

**Comment by parzival-au20** [comment]
API usage terms
Users may access their data relating to this Website via the Application Program Interface (API). Any use of the API, including use of the API through a third-party product/service that accesses this Website, is bound by these Terms and, in addition, by the following specific terms:

the User expressly understands and agrees that the Owner bears no responsibility and shall not be held liable for any damages or losses resulting from the User’s use of the API or their use of any third-party products/services that access data through the API.

**Comment by parzival-au20** [comment]
p_elements=bs4Obj.find("div", {"class": "section Section_section__9Xeml"})
            p_elements_temp = bs4Obj.select("div.section.Section_section__9Xeml>p")
            
            <div class="section Section_section__9Xeml "><div class="section--content Section_content__LH2tk"><div class="wrap ComponentWrap_wrap__f7e25"><p>Energy management company World Kinect yesterday announced plans to sell charter information platform Avinode Group to Camp Systems International for $200 million in cash. The sale includes World Kinect’s aviation software that serves the FBO market.</p>

<p>World Kinect expects the deal to close within 60 days and plans to use the proceeds to repay debt and reduce its annual run rate of interest expense by approximately $10 million, according to company executive v-p and CFO Ira Birns. “Longer term, this transaction should provide us with additional liquidity to invest in our core distribution platform and emerging sustainability offerings.”</p>

<p>Camp is a subsidiary of Hearst and specializes in aviation management services such as maintenance tracking, engine health monitoring, inventory management, and flight scheduling. Customers include more than 30,000 users and 1,500 MRO facilities supporting more than 20,000 aircraft and 30,000 engines.</p>

<p>“We are excited to acquire the Avinode Group and FBO products with their strong track record of delivering innovative, market-leading solutions,” said Camp Systems CEO Sean Lanagan. “This acquisition represents a complementary extension of our business and platform, to bring exciting new opportunities to the market and better serve our expanding customer base.”</p>
</div></div></div>

**Comment by parzival-au20** [comment]
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.190 Safari/537.36

**Comment by parzival-au20** [comment]
def create_urllib_object(self,web_site_link):
        """bu fonksiyon website htmlini okur """


        """User agentın buradan değiştirilmesi gerekiyor. """
        #self.current_user_agent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36"
        self.current_user_agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.190 Safari/537.36"
        counter=0
        while True:
           
            try:
                if counter>1000:
                    break
                link=web_site_link
                '''
                                    web.Headers[HttpRequestHeader.UserAgent] = "Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.9.2.21pre) Gecko K-Meleon/1.7.0";
                    web.Headers[HttpRequestHeader.ContentType] = "application/x-www-form-urlencoded";
                    web.Headers[HttpRequestHeader.Accept] = "application/json";

                    web.Headers[HttpRequestHeader.AcceptLanguage] = "tr-TR,q=0.8,tr;q=0.6";
                    web.Headers[HttpRequestHeader.AcceptCharset] = "UTF-8";
                '''
                req=Request(url=link,data=None,headers={ 'User-Agent': f'{self.current_user_agent}',
                                                         "Content-Type": f"text/html",
                                                        "Accept": "text/html",
                                                         "Accept-Language": "tr-TR,q=0.8,tr;q=0.6",
                                                         "Accept-Charset": "UTF-8"})
            
                self.html=urlopen(req,context=ctx)
            

                #print(self.html)
                
                break
            except HTTPError as e:
                
                print(e)

                counter=counter+1
                del self.current_user_agent
                self.current_user_agent=self.get_random_user_agent()[counter]

**Comment by parzival-au20** [comment]
[Medya_Takip_Yeni_Siteler.xlsx](https://github.com/parzival-au20/sefa/files/14664008/Medya_Takip_Yeni_Siteler.xlsx)

**Comment by parzival-au20** [comment]
19 Mart 2024, Salı 10:16:39
Ukrayna'ya ait helikopter düşürüldü!

**Comment by parzival-au20** [comment]
'Rus ordusundan Ukrayna’ya Mİ-8 helikopter kaçıran\xa0Maksim Kuzminov\xa0adlı pilot, yakın zamanda İspanya’da ölü bulundu.Rusya Dış İstihbarat Servisi Direktörü Sergey Narşkin, İspanya’da ölü bulunan pilot hakkında yorum yaptı.Kaçak hakkında Rusya Dış İstihbarat Servis Direktörü (SVR) Narşkin, “Rusya’da adettir, ölü hakkında iyi veya kötü konuşulmaz. Fakat o hain, bu kirli planı düşündüğü andan itibaren ahlaken bir ceset haline gelmişti” dedi.Pazartesi günü Ukrayna haber ajansı\xa0İspanya’nın Villajoyosa\xa0ilçesinde ölü bir beden bulunduğunu, cesetin helikopteri çalan\xa0Kuzminov’a\xa0ait olduğunu aktarmıştı.Ukrayna Savunma Bakanlığı’na bağlı\xa0GUR’dan bir temsilci de Kuzminov’un\xa0öldüğünü doğruladı.Rusya Savunma Bakanlığı konu ile ilgili yorum yapmadı.' 
burada ki \xa0 bu terimleri nasıl temizlersin bunlar &nbps çünkü veri çekerken böyle geliyor.

**Comment by parzival-au20** [comment]
' İtalya-İsviçre sınırında helikopter düştü\t\t\t '
title bu şekilde gelyor bunuda temizlemliyiz

**Comment by parzival-au20** [comment]
'17 Mart 2024'
"""pull timestamp"""
            re_pattern=r"(\w* \d{1,2} \d{4})"
            time_stamp=bs4Obj.find("time",{"class": "date-container"}).get_text()
            matched_time_stamp=re.findall(re_pattern, time_stamp)[0]
            
            
            'AirTurkHaber':['%d %B %Y',"turkish"],

**Comment by parzival-au20** [comment]
import requests
import base64

def url_to_base64(image_url):
    # Resmi URL'den indirin
    response = requests.get(image_url)
    
    # İndirilen veriyi base64'e dönüştürün
    base64_image = base64.b64encode(response.content).decode('utf-8')
    
    return base64_image

# Base64'e dönüştürmek istediğiniz resmin URL'si
image_url = "https://example.com/image.jpg"

# Fonksiyonu kullanarak resmi base64'e dönüştürün
base64_image = url_to_base64(image_url)

print(base64_image)

**Comment by parzival-au20** [comment]
Traceback (most recent call last):
  File "C:\Users\s20128\AppData\Roaming\Python\Python311\site-packages\urllib3\connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "C:\Users\s20128\AppData\Roaming\Python\Python311\site-packages\urllib3\connectionpool.py", line 1099, in _validate_conn
    conn.connect()
  File "C:\Users\s20128\AppData\Roaming\Python\Python311\site-packages\urllib3\connection.py", line 653, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\s20128\AppData\Roaming\Python\Python311\site-packages\urllib3\connection.py", line 806, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
               ^^^^^^^^^^^^^^^^
  File "C:\Users\s20128\AppData\Roaming\Python\Python311\site-packages\urllib3\util\ssl_.py", line 465, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\s20128\AppData\Roaming\Python\Python311\site-packages\urllib3\util\ssl_.py", line 509, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\ssl.py", line 517, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\ssl.py", line 1075, in _create
    self.do_handshake()
  File "C:\Python311\Lib\ssl.py", line 1346, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:992)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\s20128\AppData\Roaming\Python\Python311\site-packages\urllib3\connectionpool.py", line 793, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\s20128\AppData\Roaming\Python\Python311\site-packages\urllib3\connectionpool.py", line 491, in _make_request
    raise new_e
urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:992)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\s20128\AppData\Roaming\Python\Python311\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "C:\Users\s20128\AppData\Roaming\Python\Python311\site-packages\urllib3\connectionpool.py", line 847, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "C:\Users\s20128\AppData\Roaming\Python\Python311\site-packages\urllib3\util\retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='assets.verticalmag.com', port=443): Max retries exceeded with url: /wp-content/uploads/2023/02/THC-Dakar2023-0228.jpg (Caused by SSLError(SSLCertVerificationE
rror(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:992)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\s20128\Desktop\Selenium\Tobase64.py", line 17, in <module>
    base64_image = url_to_base64(image_url)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\s20128\Desktop\Selenium\Tobase64.py", line 6, in url_to_base64
    response = requests.get(image_url)
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\s20128\AppData\Roaming\Python\Python311\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\s20128\AppData\Roaming\Python\Python311\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\s20128\AppData\Roaming\Python\Python311\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\s20128\AppData\Roaming\Python\Python311\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\s20128\AppData\Roaming\Python\Python311\site-packages\requests\adapters.py", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='assets.verticalmag.com', port=443): Max retries exceeded with url: /wp-content/uploads/2023/02/THC-Dakar2023-0228.jpg (Caused by SSLError(SSLCertVerificationError
(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:992)')))
